title: Zipminator PQC Documentation
author: QDaria AS
logo: ""
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - substitution
    - tasklist
sphinx:
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      repository_url: https://github.com/QDaria/zipminator
      use_repository_button: true
      use_issues_button: true
repository:
  url: https://github.com/QDaria/zipminator
  branch: main
