name: zip-pqc
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - jupyter-book
  - sphinx-book-theme
  - myst-nb
  - pip
  - pip:
    - sphinx-design
    - sphinx-copybutton
