#!/bin/bash
# Generate DNS records template for zipminator.zip
# Run this to see what DNS records to configure
# ============================================================================

DOMAIN="${1:-zipminator.zip}"
IP="${2:-YOUR_SERVER_IP}"

cat << HEREDOC
============================================================================
  Zipminator Quantum-Secure Email -- DNS Records
  Domain: ${DOMAIN}
============================================================================

--- MX Record ---
${DOMAIN}.    IN  MX  10  mail.${DOMAIN}.

--- A Record ---
mail.${DOMAIN}.    IN  A    ${IP}

--- AAAA Record (if IPv6) ---
; mail.${DOMAIN}.  IN  AAAA YOUR_IPV6_ADDRESS

--- SPF Record ---
${DOMAIN}.    IN  TXT  "v=spf1 mx ip4:${IP} -all"

--- DMARC Record ---
_dmarc.${DOMAIN}.    IN  TXT  "v=DMARC1; p=quarantine; rua=mailto:dmarc@${DOMAIN}; ruf=mailto:dmarc-forensic@${DOMAIN}; pct=100; adkim=s; aspf=s"

--- DKIM RSA-2048 Record (selector: s1) ---
; Generated by opendkim-genkey during container startup.
; Check /etc/opendkim/keys/${DOMAIN}/s1.txt after first boot.
s1._domainkey.${DOMAIN}.    IN  TXT  ( "v=DKIM1; h=sha256; k=rsa; "
    "p=YOUR_RSA_PUBLIC_KEY_BASE64" )

--- DKIM ML-DSA-65 Record (selector: s1pq) --- [WORLD FIRST]
; This is the post-quantum DKIM signature selector.
; The ML-DSA-65 public key is ~2.6KB base64, requiring EDNS0 support.
; Receivers that don't understand ML-DSA will ignore this record.
; Generated by the PQ DKIM milter during container startup.
s1pq._domainkey.${DOMAIN}.    IN  TXT  ( "v=DKIM1; h=sha256; k=mldsa65; "
    "p=YOUR_MLDSA65_PUBLIC_KEY_BASE64_PART1"
    "YOUR_MLDSA65_PUBLIC_KEY_BASE64_PART2"
    "YOUR_MLDSA65_PUBLIC_KEY_BASE64_PART3"
    "YOUR_MLDSA65_PUBLIC_KEY_BASE64_PART4" )

--- MTA-STS Record ---
_mta-sts.${DOMAIN}.    IN  TXT  "v=STSv1; id=$(date +%Y%m%d%H%M%S)"

--- MTA-STS Policy (host at https://mta-sts.${DOMAIN}/.well-known/mta-sts.txt) ---
version: STSv1
mode: enforce
mx: mail.${DOMAIN}
max_age: 604800

--- TLSRPT Record ---
_smtp._tls.${DOMAIN}.    IN  TXT  "v=TLSRPTv1; rua=mailto:tls-report@${DOMAIN}"

--- SRV Records (for auto-discovery) ---
_submission._tcp.${DOMAIN}.    IN  SRV  0 1 587 mail.${DOMAIN}.
_imaps._tcp.${DOMAIN}.         IN  SRV  0 1 993 mail.${DOMAIN}.

--- Autoconfig (Thunderbird) ---
; Host XML at https://autoconfig.${DOMAIN}/mail/config-v1.1.xml

--- Autodiscover (Outlook) ---
_autodiscover._tcp.${DOMAIN}.  IN  SRV  0 1 443 autodiscover.${DOMAIN}.

============================================================================
HEREDOC
