/**
 * QRNG Integration Tests
 *
 * Comprehensive test suite for QRNG interface, drivers, and Kyber integration.
 * Tests both mock and hardware implementations.
 *
 * Test Categories:
 * 1. Interface tests (MockQRNG)
 * 2. Entropy pool tests
 * 3. Kyber integration tests
 * 4. Statistical randomness tests
 * 5. Performance tests
 * 6. Error handling tests
 */

#include "../src/cpp/qrng/qrng_interface.h"
#include "../src/cpp/qrng/mock_qrng.h"
#include "../src/cpp/qrng/entropy_pool.h"
#include "../src/cpp/kyber768.h"
#include <cassert>
#include <iostream>
#include <iomanip>
#include <vector>
#include <set>
#include <cmath>
#include <chrono>
#include <cstring>

// Forward declare QRNG Kyber functions
namespace kyber768 {
    int crypto_kem_keypair_qrng(uint8_t *pk, uint8_t *sk);
    int crypto_kem_enc_qrng(uint8_t *ct, uint8_t *ss, const uint8_t *pk);
    int crypto_kem_dec_qrng(uint8_t *ss, const uint8_t *ct, const uint8_t *sk);
}

// Test result tracking
struct TestResult {
    std::string name;
    bool passed;
    double duration_ms;
    std::string error_message;
};

std::vector<TestResult> test_results;

// Test helper macros
#define TEST(name) \
    void test_##name(); \
    void run_test_##name() { \
        auto start = std::chrono::high_resolution_clock::now(); \
        bool passed = true; \
        std::string error; \
        try { \
            test_##name(); \
        } catch (const std::exception& e) { \
            passed = false; \
            error = e.what(); \
        } \
        auto end = std::chrono::high_resolution_clock::now(); \
        double duration = std::chrono::duration<double, std::milli>(end - start).count(); \
        test_results.push_back({#name, passed, duration, error}); \
    } \
    void test_##name()

#define ASSERT(condition, message) \
    if (!(condition)) { \
        throw std::runtime_error(std::string("Assertion failed: ") + message); \
    }

#define ASSERT_EQ(a, b, message) \
    if ((a) != (b)) { \
        throw std::runtime_error(std::string("Assertion failed: ") + message + \
            " (expected " + std::to_string(b) + ", got " + std::to_string(a) + ")"); \
    }

// ============================================================================
// Test 1: MockQRNG Basic Operations
// ============================================================================

TEST(mock_qrng_initialization) {
    qrng::MockQRNG mock;

    // Should not be connected before initialization
    ASSERT(!mock.is_connected(), "Mock should not be connected initially");

    // Initialize
    qrng::QRNGStatus status = mock.initialize();
    ASSERT_EQ(status, qrng::QRNGStatus::OK, "Initialization should succeed");
    ASSERT(mock.is_connected(), "Mock should be connected after initialization");

    // Disconnect
    mock.disconnect();
    ASSERT(!mock.is_connected(), "Mock should not be connected after disconnect");
}

TEST(mock_qrng_random_generation) {
    qrng::MockQRNG mock;
    mock.initialize();

    // Generate random bytes
    uint8_t buffer[1024];
    qrng::QRNGStatus status = mock.get_random_bytes(buffer, sizeof(buffer));

    ASSERT_EQ(status, qrng::QRNGStatus::OK, "Random generation should succeed");

    // Check that bytes are not all zeros
    bool has_nonzero = false;
    for (size_t i = 0; i < sizeof(buffer); i++) {
        if (buffer[i] != 0) {
            has_nonzero = true;
            break;
        }
    }
    ASSERT(has_nonzero, "Generated bytes should not be all zeros");

    mock.disconnect();
}

TEST(mock_qrng_determinism) {
    // Two mocks with same seed should produce same output
    uint64_t seed = 0x123456789ABCDEF0ULL;

    qrng::MockQRNG mock1, mock2;
    mock1.reseed(seed);
    mock2.reseed(seed);

    mock1.initialize();
    mock2.initialize();

    uint8_t buffer1[256], buffer2[256];
    mock1.get_random_bytes(buffer1, sizeof(buffer1));
    mock2.get_random_bytes(buffer2, sizeof(buffer2));

    ASSERT(memcmp(buffer1, buffer2, sizeof(buffer1)) == 0,
           "Same seed should produce identical output");

    mock1.disconnect();
    mock2.disconnect();
}

TEST(mock_qrng_health_check) {
    qrng::MockQRNG mock;
    mock.initialize();

    qrng::QRNGStatus status = mock.health_check();
    ASSERT_EQ(status, qrng::QRNGStatus::OK, "Health check should pass");

    qrng::HealthStats stats = mock.get_health_stats();
    ASSERT(stats.health_checks_passed > 0, "Health check count should increase");

    mock.disconnect();
}

// ============================================================================
// Test 2: Entropy Pool Tests
// ============================================================================

TEST(entropy_pool_initialization) {
    auto mock = std::make_unique<qrng::MockQRNG>();
    qrng::EntropyPoolConfig config;
    config.pool_size = 4096;

    qrng::EntropyPool pool(std::move(mock), config);

    qrng::QRNGStatus status = pool.initialize();
    ASSERT_EQ(status, qrng::QRNGStatus::OK, "Pool initialization should succeed");
    ASSERT(pool.is_operational(), "Pool should be operational");

    pool.shutdown();
}

TEST(entropy_pool_random_generation) {
    auto mock = std::make_unique<qrng::MockQRNG>();
    qrng::EntropyPool pool(std::move(mock));

    pool.initialize();

    // Generate random bytes
    uint8_t buffer[2048];
    qrng::QRNGStatus status = pool.get_random_bytes(buffer, sizeof(buffer));

    ASSERT_EQ(status, qrng::QRNGStatus::OK, "Pool random generation should succeed");

    // Verify non-zero bytes
    bool has_nonzero = false;
    for (size_t i = 0; i < sizeof(buffer); i++) {
        if (buffer[i] != 0) {
            has_nonzero = true;
            break;
        }
    }
    ASSERT(has_nonzero, "Generated bytes should not be all zeros");

    pool.shutdown();
}

TEST(entropy_pool_concurrent_access) {
    auto mock = std::make_unique<qrng::MockQRNG>();
    qrng::EntropyPool pool(std::move(mock));

    pool.initialize();

    // Simulate multiple consumers
    const int num_threads = 4;
    const int bytes_per_thread = 1024;
    std::vector<std::thread> threads;
    std::atomic<int> success_count(0);

    for (int i = 0; i < num_threads; i++) {
        threads.emplace_back([&pool, &success_count, bytes_per_thread]() {
            uint8_t buffer[bytes_per_thread];
            if (pool.get_random_bytes(buffer, sizeof(buffer)) == qrng::QRNGStatus::OK) {
                success_count++;
            }
        });
    }

    for (auto& thread : threads) {
        thread.join();
    }

    ASSERT_EQ(success_count.load(), num_threads, "All threads should succeed");

    pool.shutdown();
}

TEST(entropy_pool_statistics) {
    auto mock = std::make_unique<qrng::MockQRNG>();
    qrng::EntropyPool pool(std::move(mock));

    pool.initialize();

    // Generate some data
    uint8_t buffer[4096];
    pool.get_random_bytes(buffer, sizeof(buffer));

    qrng::EntropyPoolStats stats = pool.get_stats();

    ASSERT(stats.total_bytes_served >= sizeof(buffer),
           "Statistics should track bytes served");

    pool.shutdown();
}

// ============================================================================
// Test 3: Kyber QRNG Integration Tests
// ============================================================================

TEST(kyber_qrng_keypair_generation) {
    // Initialize global entropy pool with mock
    auto mock = std::make_unique<qrng::MockQRNG>();
    qrng::GlobalEntropyPool::initialize(std::move(mock));

    uint8_t pk[kyber768::KYBER_PUBLICKEYBYTES];
    uint8_t sk[kyber768::KYBER_SECRETKEYBYTES];

    int result = kyber768::crypto_kem_keypair_qrng(pk, sk);
    ASSERT_EQ(result, 0, "Keypair generation should succeed");

    // Verify keys are not all zeros
    bool pk_nonzero = false, sk_nonzero = false;

    for (size_t i = 0; i < sizeof(pk); i++) {
        if (pk[i] != 0) pk_nonzero = true;
    }

    for (size_t i = 0; i < sizeof(sk); i++) {
        if (sk[i] != 0) sk_nonzero = true;
    }

    ASSERT(pk_nonzero, "Public key should not be all zeros");
    ASSERT(sk_nonzero, "Secret key should not be all zeros");

    qrng::GlobalEntropyPool::shutdown();
}

TEST(kyber_qrng_full_kem_cycle) {
    // Initialize global entropy pool
    auto mock = std::make_unique<qrng::MockQRNG>();
    qrng::GlobalEntropyPool::initialize(std::move(mock));

    // Generate keypair
    uint8_t pk[kyber768::KYBER_PUBLICKEYBYTES];
    uint8_t sk[kyber768::KYBER_SECRETKEYBYTES];
    ASSERT_EQ(kyber768::crypto_kem_keypair_qrng(pk, sk), 0,
              "Keypair generation failed");

    // Encapsulate
    uint8_t ct[kyber768::KYBER_CIPHERTEXTBYTES];
    uint8_t ss_enc[kyber768::KYBER_SHAREDSECRETBYTES];
    ASSERT_EQ(kyber768::crypto_kem_enc_qrng(ct, ss_enc, pk), 0,
              "Encapsulation failed");

    // Decapsulate
    uint8_t ss_dec[kyber768::KYBER_SHAREDSECRETBYTES];
    ASSERT_EQ(kyber768::crypto_kem_dec_qrng(ss_dec, ct, sk), 0,
              "Decapsulation failed");

    // Verify shared secrets match
    ASSERT(memcmp(ss_enc, ss_dec, kyber768::KYBER_SHAREDSECRETBYTES) == 0,
           "Shared secrets should match");

    qrng::GlobalEntropyPool::shutdown();
}

TEST(kyber_qrng_deterministic_with_seed) {
    // Two runs with same seed should produce same keypairs
    uint64_t seed = 0xDEADBEEFCAFEBABEULL;

    uint8_t pk1[kyber768::KYBER_PUBLICKEYBYTES];
    uint8_t sk1[kyber768::KYBER_SECRETKEYBYTES];

    uint8_t pk2[kyber768::KYBER_PUBLICKEYBYTES];
    uint8_t sk2[kyber768::KYBER_SECRETKEYBYTES];

    // First run
    {
        auto mock = qrng::create_mock_qrng(seed);
        qrng::GlobalEntropyPool::initialize(std::move(mock));
        kyber768::crypto_kem_keypair_qrng(pk1, sk1);
        qrng::GlobalEntropyPool::shutdown();
    }

    // Second run with same seed
    {
        auto mock = qrng::create_mock_qrng(seed);
        qrng::GlobalEntropyPool::initialize(std::move(mock));
        kyber768::crypto_kem_keypair_qrng(pk2, sk2);
        qrng::GlobalEntropyPool::shutdown();
    }

    ASSERT(memcmp(pk1, pk2, sizeof(pk1)) == 0, "Public keys should match");
    ASSERT(memcmp(sk1, sk2, sizeof(sk1)) == 0, "Secret keys should match");
}

// ============================================================================
// Test 4: Statistical Randomness Tests (Simplified NIST SP 800-22)
// ============================================================================

TEST(statistical_frequency_test) {
    qrng::MockQRNG mock;
    mock.initialize();

    // Generate test data
    const size_t test_size = 10000;
    uint8_t data[test_size];
    mock.get_random_bytes(data, test_size);

    // Count bit frequencies
    size_t ones = 0, zeros = 0;

    for (size_t i = 0; i < test_size; i++) {
        for (int bit = 0; bit < 8; bit++) {
            if ((data[i] >> bit) & 1) {
                ones++;
            } else {
                zeros++;
            }
        }
    }

    // Should be roughly 50/50 (within 5% tolerance)
    size_t total_bits = test_size * 8;
    double ones_ratio = (double)ones / total_bits;

    ASSERT(ones_ratio > 0.45 && ones_ratio < 0.55,
           "Bit frequency should be balanced");

    mock.disconnect();
}

TEST(statistical_runs_test) {
    qrng::MockQRNG mock;
    mock.initialize();

    const size_t test_size = 1000;
    uint8_t data[test_size];
    mock.get_random_bytes(data, test_size);

    // Count runs of identical bytes
    size_t max_run = 1;
    size_t current_run = 1;

    for (size_t i = 1; i < test_size; i++) {
        if (data[i] == data[i-1]) {
            current_run++;
            if (current_run > max_run) {
                max_run = current_run;
            }
        } else {
            current_run = 1;
        }
    }

    // Maximum run should not be excessive (< 10 for 1000 bytes)
    ASSERT(max_run < 10, "Maximum run length should be reasonable");

    mock.disconnect();
}

TEST(statistical_uniqueness_test) {
    qrng::MockQRNG mock;
    mock.initialize();

    const size_t test_size = 256;
    uint8_t data[test_size];
    mock.get_random_bytes(data, test_size);

    // Count unique bytes
    std::set<uint8_t> unique_bytes(data, data + test_size);

    // Should see significant variety (at least 200/256 unique)
    ASSERT(unique_bytes.size() >= 200,
           "Should have good byte diversity");

    mock.disconnect();
}

// ============================================================================
// Test 5: Performance Tests
// ============================================================================

TEST(performance_mock_qrng_throughput) {
    qrng::MockQRNG mock;
    mock.initialize();

    const size_t test_size = 1024 * 1024;  // 1 MB
    std::vector<uint8_t> buffer(test_size);

    auto start = std::chrono::high_resolution_clock::now();
    mock.get_random_bytes(buffer.data(), test_size);
    auto end = std::chrono::high_resolution_clock::now();

    double duration_ms = std::chrono::duration<double, std::milli>(end - start).count();
    double throughput_mbps = (test_size / (1024.0 * 1024.0)) / (duration_ms / 1000.0);

    std::cout << "  Mock QRNG Throughput: " << throughput_mbps << " MB/s" << std::endl;

    // Should be reasonably fast (> 10 MB/s)
    ASSERT(throughput_mbps > 10.0, "Throughput should be reasonable");

    mock.disconnect();
}

TEST(performance_entropy_pool_latency) {
    auto mock = std::make_unique<qrng::MockQRNG>();
    qrng::EntropyPool pool(std::move(mock));
    pool.initialize();

    // Measure latency for small requests (already buffered)
    const int iterations = 1000;
    uint8_t buffer[32];

    auto start = std::chrono::high_resolution_clock::now();
    for (int i = 0; i < iterations; i++) {
        pool.get_random_bytes(buffer, sizeof(buffer));
    }
    auto end = std::chrono::high_resolution_clock::now();

    double total_us = std::chrono::duration<double, std::micro>(end - start).count();
    double avg_latency_us = total_us / iterations;

    std::cout << "  Entropy Pool Avg Latency: " << avg_latency_us << " μs" << std::endl;

    // Should be very fast when buffered (< 10 μs)
    ASSERT(avg_latency_us < 10.0, "Buffered access should be fast");

    pool.shutdown();
}

// ============================================================================
// Test 6: Error Handling Tests
// ============================================================================

TEST(error_handling_uninitialized_pool) {
    // Try to use pool without initializing global instance
    // (Assuming it's not initialized or we shut it down first)
    qrng::GlobalEntropyPool::shutdown();

    // This should fail gracefully
    uint8_t pk[kyber768::KYBER_PUBLICKEYBYTES];
    uint8_t sk[kyber768::KYBER_SECRETKEYBYTES];

    int result = kyber768::crypto_kem_keypair_qrng(pk, sk);
    ASSERT_EQ(result, -1, "Should fail without initialized pool");
}

TEST(error_handling_null_buffer) {
    qrng::MockQRNG mock;
    mock.initialize();

    qrng::QRNGStatus status = mock.get_random_bytes(nullptr, 100);
    ASSERT(status != qrng::QRNGStatus::OK, "Should fail with null buffer");

    mock.disconnect();
}

// ============================================================================
// Test Runner
// ============================================================================

void run_all_tests() {
    std::cout << "\n========================================" << std::endl;
    std::cout << "QRNG Integration Test Suite" << std::endl;
    std::cout << "========================================\n" << std::endl;

    // Run all tests
    run_test_mock_qrng_initialization();
    run_test_mock_qrng_random_generation();
    run_test_mock_qrng_determinism();
    run_test_mock_qrng_health_check();

    run_test_entropy_pool_initialization();
    run_test_entropy_pool_random_generation();
    run_test_entropy_pool_concurrent_access();
    run_test_entropy_pool_statistics();

    run_test_kyber_qrng_keypair_generation();
    run_test_kyber_qrng_full_kem_cycle();
    run_test_kyber_qrng_deterministic_with_seed();

    run_test_statistical_frequency_test();
    run_test_statistical_runs_test();
    run_test_statistical_uniqueness_test();

    run_test_performance_mock_qrng_throughput();
    run_test_performance_entropy_pool_latency();

    run_test_error_handling_uninitialized_pool();
    run_test_error_handling_null_buffer();

    // Print results
    std::cout << "\n========================================" << std::endl;
    std::cout << "Test Results" << std::endl;
    std::cout << "========================================\n" << std::endl;

    int passed = 0, failed = 0;
    double total_time = 0;

    for (const auto& result : test_results) {
        std::string status = result.passed ? "\033[32mPASS\033[0m" : "\033[31mFAIL\033[0m";
        std::cout << "[" << status << "] " << std::left << std::setw(45)
                  << result.name << " (" << std::fixed << std::setprecision(2)
                  << result.duration_ms << " ms)" << std::endl;

        if (!result.passed) {
            std::cout << "       Error: " << result.error_message << std::endl;
            failed++;
        } else {
            passed++;
        }

        total_time += result.duration_ms;
    }

    std::cout << "\n========================================" << std::endl;
    std::cout << "Summary: " << passed << " passed, " << failed << " failed" << std::endl;
    std::cout << "Total time: " << total_time << " ms" << std::endl;
    std::cout << "========================================\n" << std::endl;
}

int main() {
    run_all_tests();

    // Return non-zero if any tests failed
    for (const auto& result : test_results) {
        if (!result.passed) {
            return 1;
        }
    }

    return 0;
}
