// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 2103773269;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_zipminator',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<KeypairResult> crateApiSimpleCompositeKeypair();

  Future<Uint8List> crateApiSimpleDecapsulate({
    required List<int> ciphertext,
    required List<int> secretKey,
  });

  Future<SrtpKeysResult> crateApiSimpleDeriveSrtpKeys({
    required List<int> sharedSecret,
  });

  Future<Uint8List> crateApiSimpleEmailDecrypt({
    required List<int> secretKey,
    required List<int> envelope,
    required List<int> aad,
  });

  Future<Uint8List> crateApiSimpleEmailEncrypt({
    required List<int> recipientPk,
    required List<int> plaintext,
    required List<int> aad,
  });

  Future<EncapsulationResult> crateApiSimpleEncapsulate({
    required List<int> publicKey,
  });

  Future<void> crateApiSimpleInitApp();

  Future<KeypairResult> crateApiSimpleKeypair();

  String crateApiSimplePiiScan({
    required String text,
    required String countryCodes,
  });

  Future<void> crateApiSimpleRatchetAliceFinish({
    required BigInt sessionId,
    required List<int> kemCiphertext,
    required List<int> bobPublicKey,
  });

  Future<Uint8List> crateApiSimpleRatchetDecrypt({
    required BigInt sessionId,
    required List<int> header,
    required List<int> ciphertext,
  });

  void crateApiSimpleRatchetDestroy({required BigInt sessionId});

  Future<RatchetMessage> crateApiSimpleRatchetEncrypt({
    required BigInt sessionId,
    required List<int> plaintext,
  });

  Future<RatchetAliceResult> crateApiSimpleRatchetInitAlice();

  Future<RatchetBobResult> crateApiSimpleRatchetInitBob({
    required List<int> alicePublicKey,
  });

  String crateApiSimpleVersion();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<KeypairResult> crateApiSimpleCompositeKeypair() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_keypair_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCompositeKeypairConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCompositeKeypairConstMeta =>
      const TaskConstMeta(debugName: "composite_keypair", argNames: []);

  @override
  Future<Uint8List> crateApiSimpleDecapsulate({
    required List<int> ciphertext,
    required List<int> secretKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          sse_encode_list_prim_u_8_loose(secretKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDecapsulateConstMeta,
        argValues: [ciphertext, secretKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDecapsulateConstMeta => const TaskConstMeta(
    debugName: "decapsulate",
    argNames: ["ciphertext", "secretKey"],
  );

  @override
  Future<SrtpKeysResult> crateApiSimpleDeriveSrtpKeys({
    required List<int> sharedSecret,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(sharedSecret, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_srtp_keys_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDeriveSrtpKeysConstMeta,
        argValues: [sharedSecret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDeriveSrtpKeysConstMeta =>
      const TaskConstMeta(
        debugName: "derive_srtp_keys",
        argNames: ["sharedSecret"],
      );

  @override
  Future<Uint8List> crateApiSimpleEmailDecrypt({
    required List<int> secretKey,
    required List<int> envelope,
    required List<int> aad,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(secretKey, serializer);
          sse_encode_list_prim_u_8_loose(envelope, serializer);
          sse_encode_list_prim_u_8_loose(aad, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEmailDecryptConstMeta,
        argValues: [secretKey, envelope, aad],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEmailDecryptConstMeta => const TaskConstMeta(
    debugName: "email_decrypt",
    argNames: ["secretKey", "envelope", "aad"],
  );

  @override
  Future<Uint8List> crateApiSimpleEmailEncrypt({
    required List<int> recipientPk,
    required List<int> plaintext,
    required List<int> aad,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(recipientPk, serializer);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          sse_encode_list_prim_u_8_loose(aad, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEmailEncryptConstMeta,
        argValues: [recipientPk, plaintext, aad],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEmailEncryptConstMeta => const TaskConstMeta(
    debugName: "email_encrypt",
    argNames: ["recipientPk", "plaintext", "aad"],
  );

  @override
  Future<EncapsulationResult> crateApiSimpleEncapsulate({
    required List<int> publicKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(publicKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_encapsulation_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncapsulateConstMeta,
        argValues: [publicKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncapsulateConstMeta =>
      const TaskConstMeta(debugName: "encapsulate", argNames: ["publicKey"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<KeypairResult> crateApiSimpleKeypair() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_keypair_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleKeypairConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleKeypairConstMeta =>
      const TaskConstMeta(debugName: "keypair", argNames: []);

  @override
  String crateApiSimplePiiScan({
    required String text,
    required String countryCodes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_String(countryCodes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePiiScanConstMeta,
        argValues: [text, countryCodes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePiiScanConstMeta => const TaskConstMeta(
    debugName: "pii_scan",
    argNames: ["text", "countryCodes"],
  );

  @override
  Future<void> crateApiSimpleRatchetAliceFinish({
    required BigInt sessionId,
    required List<int> kemCiphertext,
    required List<int> bobPublicKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_list_prim_u_8_loose(kemCiphertext, serializer);
          sse_encode_list_prim_u_8_loose(bobPublicKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleRatchetAliceFinishConstMeta,
        argValues: [sessionId, kemCiphertext, bobPublicKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRatchetAliceFinishConstMeta =>
      const TaskConstMeta(
        debugName: "ratchet_alice_finish",
        argNames: ["sessionId", "kemCiphertext", "bobPublicKey"],
      );

  @override
  Future<Uint8List> crateApiSimpleRatchetDecrypt({
    required BigInt sessionId,
    required List<int> header,
    required List<int> ciphertext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_list_prim_u_8_loose(header, serializer);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleRatchetDecryptConstMeta,
        argValues: [sessionId, header, ciphertext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRatchetDecryptConstMeta =>
      const TaskConstMeta(
        debugName: "ratchet_decrypt",
        argNames: ["sessionId", "header", "ciphertext"],
      );

  @override
  void crateApiSimpleRatchetDestroy({required BigInt sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleRatchetDestroyConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRatchetDestroyConstMeta =>
      const TaskConstMeta(
        debugName: "ratchet_destroy",
        argNames: ["sessionId"],
      );

  @override
  Future<RatchetMessage> crateApiSimpleRatchetEncrypt({
    required BigInt sessionId,
    required List<int> plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ratchet_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleRatchetEncryptConstMeta,
        argValues: [sessionId, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRatchetEncryptConstMeta =>
      const TaskConstMeta(
        debugName: "ratchet_encrypt",
        argNames: ["sessionId", "plaintext"],
      );

  @override
  Future<RatchetAliceResult> crateApiSimpleRatchetInitAlice() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ratchet_alice_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleRatchetInitAliceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRatchetInitAliceConstMeta =>
      const TaskConstMeta(debugName: "ratchet_init_alice", argNames: []);

  @override
  Future<RatchetBobResult> crateApiSimpleRatchetInitBob({
    required List<int> alicePublicKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(alicePublicKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ratchet_bob_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleRatchetInitBobConstMeta,
        argValues: [alicePublicKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRatchetInitBobConstMeta =>
      const TaskConstMeta(
        debugName: "ratchet_init_bob",
        argNames: ["alicePublicKey"],
      );

  @override
  String crateApiSimpleVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleVersionConstMeta =>
      const TaskConstMeta(debugName: "version", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  EncapsulationResult dco_decode_encapsulation_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EncapsulationResult(
      ciphertext: dco_decode_list_prim_u_8_strict(arr[0]),
      sharedSecret: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  KeypairResult dco_decode_keypair_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KeypairResult(
      publicKey: dco_decode_list_prim_u_8_strict(arr[0]),
      secretKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  RatchetAliceResult dco_decode_ratchet_alice_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RatchetAliceResult(
      sessionId: dco_decode_u_64(arr[0]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  RatchetBobResult dco_decode_ratchet_bob_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RatchetBobResult(
      sessionId: dco_decode_u_64(arr[0]),
      kemCiphertext: dco_decode_list_prim_u_8_strict(arr[1]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  RatchetMessage dco_decode_ratchet_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RatchetMessage(
      header: dco_decode_list_prim_u_8_strict(arr[0]),
      ciphertext: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  SrtpKeysResult dco_decode_srtp_keys_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SrtpKeysResult(
      masterKey: dco_decode_list_prim_u_8_strict(arr[0]),
      masterSalt: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  EncapsulationResult sse_decode_encapsulation_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ciphertext = sse_decode_list_prim_u_8_strict(deserializer);
    var var_sharedSecret = sse_decode_list_prim_u_8_strict(deserializer);
    return EncapsulationResult(
      ciphertext: var_ciphertext,
      sharedSecret: var_sharedSecret,
    );
  }

  @protected
  KeypairResult sse_decode_keypair_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_secretKey = sse_decode_list_prim_u_8_strict(deserializer);
    return KeypairResult(publicKey: var_publicKey, secretKey: var_secretKey);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  RatchetAliceResult sse_decode_ratchet_alice_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_u_64(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return RatchetAliceResult(
      sessionId: var_sessionId,
      publicKey: var_publicKey,
    );
  }

  @protected
  RatchetBobResult sse_decode_ratchet_bob_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_u_64(deserializer);
    var var_kemCiphertext = sse_decode_list_prim_u_8_strict(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return RatchetBobResult(
      sessionId: var_sessionId,
      kemCiphertext: var_kemCiphertext,
      publicKey: var_publicKey,
    );
  }

  @protected
  RatchetMessage sse_decode_ratchet_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_header = sse_decode_list_prim_u_8_strict(deserializer);
    var var_ciphertext = sse_decode_list_prim_u_8_strict(deserializer);
    return RatchetMessage(header: var_header, ciphertext: var_ciphertext);
  }

  @protected
  SrtpKeysResult sse_decode_srtp_keys_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_masterKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_masterSalt = sse_decode_list_prim_u_8_strict(deserializer);
    return SrtpKeysResult(masterKey: var_masterKey, masterSalt: var_masterSalt);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_encapsulation_result(
    EncapsulationResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.ciphertext, serializer);
    sse_encode_list_prim_u_8_strict(self.sharedSecret, serializer);
  }

  @protected
  void sse_encode_keypair_result(KeypairResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.secretKey, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_ratchet_alice_result(
    RatchetAliceResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sessionId, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
  }

  @protected
  void sse_encode_ratchet_bob_result(
    RatchetBobResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sessionId, serializer);
    sse_encode_list_prim_u_8_strict(self.kemCiphertext, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
  }

  @protected
  void sse_encode_ratchet_message(
    RatchetMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.header, serializer);
    sse_encode_list_prim_u_8_strict(self.ciphertext, serializer);
  }

  @protected
  void sse_encode_srtp_keys_result(
    SrtpKeysResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.masterKey, serializer);
    sse_encode_list_prim_u_8_strict(self.masterSalt, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
