// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Library version.
String version() => RustLib.instance.api.crateApiSimpleVersion();

/// Generate an ML-KEM-768 keypair.
/// Returns (public_key: 1184 bytes, secret_key: 2400 bytes).
Future<KeypairResult> keypair() => RustLib.instance.api.crateApiSimpleKeypair();

/// Encapsulate: create a shared secret for the given public key.
/// Returns (ciphertext: 1088 bytes, shared_secret: 32 bytes).
Future<EncapsulationResult> encapsulate({required List<int> publicKey}) =>
    RustLib.instance.api.crateApiSimpleEncapsulate(publicKey: publicKey);

/// Decapsulate: recover the shared secret from ciphertext + secret key.
/// Returns 32-byte shared secret.
Future<Uint8List> decapsulate({
  required List<int> ciphertext,
  required List<int> secretKey,
}) => RustLib.instance.api.crateApiSimpleDecapsulate(
  ciphertext: ciphertext,
  secretKey: secretKey,
);

/// Generate a composite keypair (ML-KEM-768 + X25519).
/// Returns (public_key: 1216 bytes, secret_key: 2432 bytes).
Future<KeypairResult> compositeKeypair() =>
    RustLib.instance.api.crateApiSimpleCompositeKeypair();

/// Initialize Alice's side of a ratchet session.
/// Returns session_id and Alice's ephemeral public key (1184 bytes).
Future<RatchetAliceResult> ratchetInitAlice() =>
    RustLib.instance.api.crateApiSimpleRatchetInitAlice();

/// Initialize Bob's side given Alice's public key.
/// Returns session_id, KEM ciphertext (1088), and Bob's public key (1184).
Future<RatchetBobResult> ratchetInitBob({required List<int> alicePublicKey}) =>
    RustLib.instance.api.crateApiSimpleRatchetInitBob(
      alicePublicKey: alicePublicKey,
    );

/// Complete Alice's handshake with Bob's response.
Future<void> ratchetAliceFinish({
  required BigInt sessionId,
  required List<int> kemCiphertext,
  required List<int> bobPublicKey,
}) => RustLib.instance.api.crateApiSimpleRatchetAliceFinish(
  sessionId: sessionId,
  kemCiphertext: kemCiphertext,
  bobPublicKey: bobPublicKey,
);

/// Encrypt a message in a ratchet session.
/// Returns (header, ciphertext).
Future<RatchetMessage> ratchetEncrypt({
  required BigInt sessionId,
  required List<int> plaintext,
}) => RustLib.instance.api.crateApiSimpleRatchetEncrypt(
  sessionId: sessionId,
  plaintext: plaintext,
);

/// Decrypt a message in a ratchet session.
Future<Uint8List> ratchetDecrypt({
  required BigInt sessionId,
  required List<int> header,
  required List<int> ciphertext,
}) => RustLib.instance.api.crateApiSimpleRatchetDecrypt(
  sessionId: sessionId,
  header: header,
  ciphertext: ciphertext,
);

/// Destroy a ratchet session.
void ratchetDestroy({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiSimpleRatchetDestroy(sessionId: sessionId);

/// Derive SRTP key material from a 32-byte shared secret.
/// Returns (master_key: 16 bytes, master_salt: 14 bytes).
Future<SrtpKeysResult> deriveSrtpKeys({required List<int> sharedSecret}) =>
    RustLib.instance.api.crateApiSimpleDeriveSrtpKeys(
      sharedSecret: sharedSecret,
    );

/// Scan text for PII patterns.
/// Returns a JSON array of matches.
String piiScan({required String text, required String countryCodes}) => RustLib
    .instance
    .api
    .crateApiSimplePiiScan(text: text, countryCodes: countryCodes);

/// Encrypt an email body with ML-KEM-768 envelope encryption.
Future<Uint8List> emailEncrypt({
  required List<int> recipientPk,
  required List<int> plaintext,
  required List<int> aad,
}) => RustLib.instance.api.crateApiSimpleEmailEncrypt(
  recipientPk: recipientPk,
  plaintext: plaintext,
  aad: aad,
);

/// Decrypt an email envelope.
Future<Uint8List> emailDecrypt({
  required List<int> secretKey,
  required List<int> envelope,
  required List<int> aad,
}) => RustLib.instance.api.crateApiSimpleEmailDecrypt(
  secretKey: secretKey,
  envelope: envelope,
  aad: aad,
);

class EncapsulationResult {
  final Uint8List ciphertext;
  final Uint8List sharedSecret;

  const EncapsulationResult({
    required this.ciphertext,
    required this.sharedSecret,
  });

  @override
  int get hashCode => ciphertext.hashCode ^ sharedSecret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncapsulationResult &&
          runtimeType == other.runtimeType &&
          ciphertext == other.ciphertext &&
          sharedSecret == other.sharedSecret;
}

class KeypairResult {
  final Uint8List publicKey;
  final Uint8List secretKey;

  const KeypairResult({required this.publicKey, required this.secretKey});

  @override
  int get hashCode => publicKey.hashCode ^ secretKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeypairResult &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          secretKey == other.secretKey;
}

class RatchetAliceResult {
  final BigInt sessionId;
  final Uint8List publicKey;

  const RatchetAliceResult({required this.sessionId, required this.publicKey});

  @override
  int get hashCode => sessionId.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RatchetAliceResult &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          publicKey == other.publicKey;
}

class RatchetBobResult {
  final BigInt sessionId;
  final Uint8List kemCiphertext;
  final Uint8List publicKey;

  const RatchetBobResult({
    required this.sessionId,
    required this.kemCiphertext,
    required this.publicKey,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ kemCiphertext.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RatchetBobResult &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          kemCiphertext == other.kemCiphertext &&
          publicKey == other.publicKey;
}

class RatchetMessage {
  final Uint8List header;
  final Uint8List ciphertext;

  const RatchetMessage({required this.header, required this.ciphertext});

  @override
  int get hashCode => header.hashCode ^ ciphertext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RatchetMessage &&
          runtimeType == other.runtimeType &&
          header == other.header &&
          ciphertext == other.ciphertext;
}

class SrtpKeysResult {
  final Uint8List masterKey;
  final Uint8List masterSalt;

  const SrtpKeysResult({required this.masterKey, required this.masterSalt});

  @override
  int get hashCode => masterKey.hashCode ^ masterSalt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SrtpKeysResult &&
          runtimeType == other.runtimeType &&
          masterKey == other.masterKey &&
          masterSalt == other.masterSalt;
}
